# Generated by Django 4.2.24 on 2025-09-24 13:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0005_equipment_electronics_not_for_training'),
        ('programs', '0003_program_focus_areas_requires_national_alignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('nature_of_project', models.CharField(choices=[('research', 'Research'), ('prototype', 'Prototype'), ('applied', 'Applied Work')], max_length=100)),
                ('description', models.TextField()),
                ('innovation_focus', models.CharField(help_text='IoT devices, smart home, renewable energy', max_length=255)),
                ('prototype_stage', models.CharField(choices=[('concept', 'Concept'), ('prototype', 'Prototype'), ('mvp', 'MVP'), ('launch', 'Market Launch')], max_length=100)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='in_progress', max_length=100)),
                ('testing_requirements', models.TextField(blank=True, null=True)),
                ('commercialization_plan', models.TextField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='facilities.facility')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='programs.program')),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('artifact_link', models.URLField(blank=True, null=True)),
                ('outcome_type', models.CharField(choices=[('cad', 'CAD'), ('pcb', 'PCB'), ('prototype', 'Prototype'), ('report', 'Report'), ('business_plan', 'Business Plan')], max_length=100)),
                ('quality_certification', models.CharField(blank=True, max_length=255, null=True)),
                ('commercialization_status', models.CharField(blank=True, choices=[('demoed', 'Demoed'), ('market_linked', 'Market Linked'), ('launched', 'Launched')], max_length=100, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('program', 'title'), name='unique_project_title_per_program'),
        ),
    ]
