# Generated by Django 4.2.24 on 2025-09-21 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_alter_equipment_facility_alter_service_facility'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='facilities.facility'),
        ),
    ]
