# Generated by Django 5.2.5 on 2025-09-16 07:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('partner_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('facility_type', models.CharField(choices=[('lab', 'Lab'), ('workshop', 'Workshop'), ('testing', 'Testing Center')], max_length=100)),
                ('capabilities', models.TextField(help_text='e.g., CNC, PCB fabrication, materials testing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('capabilities', models.TextField()),
                ('description', models.TextField()),
                ('inventory_code', models.CharField(max_length=100, unique=True)),
                ('usage_domain', models.CharField(choices=[('electronics', 'Electronics'), ('mechanical', 'Mechanical'), ('iot', 'IoT'), ('robotics', 'Robotics'), ('software', 'Software')], max_length=100)),
                ('support_phase', models.CharField(choices=[('training', 'Training'), ('prototyping', 'Prototyping'), ('testing', 'Testing'), ('commercialization', 'Commercialization')], max_length=100)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='facilities.facility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('machining', 'Machining'), ('testing', 'Testing'), ('training', 'Training')], max_length=100)),
                ('skill_type', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('integration', 'Integration')], max_length=100)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='facilities.facility')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
