# Generated by Django 4.2.24 on 2025-09-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.UniqueConstraint(fields=('name', 'location'), name='unique_facility_name_location'),
        ),
    ]
