# Generated by Django 4.2.24 on 2025-09-21 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_unique_facility_name_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='facilities.facility'),
        ),
        migrations.AlterField(
            model_name='service',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='facilities.facility'),
        ),
    ]
