# Generated by Django 4.2.24 on 2025-09-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_alter_equipment_facility_alter_service_facility'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('facility', 'name'), name='unique_service_name_per_facility'),
        ),
    ]
