# Generated by Django 4.2.24 on 2025-09-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_service_unique_service_name_per_facility'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.CheckConstraint(check=models.Q(('usage_domain', 'electronics'), ('support_phase', 'training'), _negated=True), name='electronics_not_for_training'),
        ),
    ]
