# Generated by Django 4.2.24 on 2025-09-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_program_description'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(check=models.Q(('focus_areas__isnull', False), ('national_alignment__isnull', True), _connector='OR'), name='focus_areas_requires_national_alignment'),
        ),
    ]
